import nacl from 'tweetnacl';

function base64Encode(bytes: Uint8Array): string {
  return btoa(String.fromCharCode(...bytes));
}

export interface WireGuardConfig {
  server: {
    privateKey: string;
    publicKey: string;
    address: string;
    listenPort: number;
    postUp: string;
    postDown: string;
  };
  clients: {
    index: number;
    privateKey: string;
    publicKey: string;
    presharedKey: string;
    address: string;
    allowedIPs: string;
    dns: string;
    keepalive: number;
    showQR: boolean;
  }[];
}

export function generateKeyPair(): { publicKey: string; privateKey: string } {
  const kp = nacl.box.keyPair();
  return {
    publicKey: base64Encode(kp.publicKey),
    privateKey: base64Encode(kp.secretKey),
  };
}

export function generatePresharedKey(): string {
  return base64Encode(nacl.randomBytes(32));
}

export function generateServerConfig(config: WireGuardConfig): string {
  const lines: string[] = [
    '# WireGuard Server Configuration',
    '# Generated by WireGuard Configurator',
    '',
    '[Interface]',
    `PrivateKey = ${config.server.privateKey}`,
    `Address = ${config.server.address}`,
    `ListenPort = ${config.server.listenPort}`,
  ];

  if (config.server.postUp) {
    lines.push(`PostUp = ${config.server.postUp}`);
  }
  if (config.server.postDown) {
    lines.push(`PostDown = ${config.server.postDown}`);
  }

  lines.push('');

  for (const client of config.clients) {
    lines.push(`# Client ${client.index}`);
    lines.push('[Peer]');
    lines.push(`PublicKey = ${client.publicKey}`);
    if (client.presharedKey) {
      lines.push(`PresharedKey = ${client.presharedKey}`);
    }
    lines.push(`AllowedIPs = ${client.allowedIPs}`);
    lines.push('');
  }

  return lines.join('\n');
}

export function generateClientConfig(
  serverPublicKey: string,
  serverEndpoint: string,
  serverListenPort: number,
  client: WireGuardConfig['clients'][0],
): string {
  const lines: string[] = [
    '# WireGuard Client Configuration',
    '# Generated by WireGuard Configurator',
    '',
    '[Interface]',
    `PrivateKey = ${client.privateKey}`,
    `Address = ${client.address}`,
  ];

  if (client.dns) {
    lines.push(`DNS = ${client.dns}`);
  }

  lines.push('');
  lines.push('[Peer]');
  lines.push(`PublicKey = ${serverPublicKey}`);
  lines.push(`Endpoint = ${serverEndpoint}:${serverListenPort}`);

  if (client.presharedKey) {
    lines.push(`PresharedKey = ${client.presharedKey}`);
  }

  lines.push(`AllowedIPs = ${client.allowedIPs}`);

  if (client.keepalive > 0) {
    lines.push(`PersistentKeepalive = ${client.keepalive}`);
  }

  lines.push('');
  return lines.join('\n');
}

export function generateAllClientConfigs(
  config: WireGuardConfig,
  serverEndpoint: string,
): string[] {
  return config.clients.map((client) =>
    generateClientConfig(
      config.server.publicKey,
      serverEndpoint,
      config.server.listenPort,
      client,
    ),
  );
}
